### ISSUE TITLE
v1.3 roadmap, ideas

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Icon-fonts#21]
With the forthcoming release of the EBI Visual Framework v1.3, we're looking to roll a v1.3 of the EBI Icon Fonts. 

These won't be peer dependencies, but they would pair nicely.

What's on offer:
- [x] More icons at last! The request backlog is long, and we're overdue to add some useful functional icons (up/down, full screen, file icons and so on). We're consolidating common fonts into EBI-Common and adding non-redundant FontAwesome icons. #22
- [x] Availability as a class. Currently you must use a `data-icon=""` attribute, would also be good to expose the class, `class="icon icon-generic icon-generic-handshake`
- [X] Under the hood pipeline improvements, such as getting the gallery onto the EBI Style Lab
- [X] Drop all but WOFF/WOFF2 #17

Bumped to v1.4:
- [ ] Semantic variants: i.e. The industry icon should only be use for "industry", for other cases we should make available as "handshake" ![image](https://user-images.githubusercontent.com/928100/36199013-2ac12d94-1170-11e8-912e-0b593b0dea8a.png)

Other requests? Ideas? Comment? Add them below.

See the demo: https://www.ebi.ac.uk/style-lab/general/fonts/v1.3/

**Comment by khawkins98** [comment]
We've now completed the various requests/bugs for v1.3 (https://github.com/ebiwd/EBI-Icon-fonts/milestone/2).

Plan is to roll a RC this week and perhaps a final release at next month's Web Guidelines Committee (4 September) and then begin planning for v1.4.
